# Generated by Django 2.0.2 on 2018-03-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('tel', models.CharField(default=0, max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('civility', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('gouvernorate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=0, max_length=100)),
                ('dateAjout', models.DateField()),
                ('nature', models.CharField(max_length=50)),
                ('duree', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('salaire', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('tel', models.CharField(default=0, max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('entrepriseName', models.CharField(max_length=50)),
                ('webSite', models.CharField(max_length=50)),
                ('emplacement', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('secteur', models.CharField(max_length=50)),
                ('nbEmployee', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='offre',
            name='idRecruteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrumboard.Recruteur', verbose_name='idRecruteur'),
        ),
    ]
