# Generated by Django 2.0.2 on 2018-04-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_auto_20180405_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
