# Generated by Django 2.0.2 on 2018-04-06 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0003_auto_20180406_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Offre', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
