# Generated by Django 2.0.2 on 2018-03-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0003_auto_20180331_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruteur',
            name='id',
        ),
        migrations.AddField(
            model_name='recruteur',
            name='recruteur_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='Recruteur id'),
            preserve_default=False,
        ),
    ]
