# Generated by Django 2.0.2 on 2018-03-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0003_card_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=50)),
                ('civility', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('gouvernorate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=50)),
                ('entrepriseName', models.CharField(max_length=50)),
                ('webSite', models.CharField(max_length=50)),
                ('emplacement', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='uploads/')),
                ('description', models.CharField(max_length=50)),
                ('secteur', models.CharField(max_length=50)),
                ('nbEmployee', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='list',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
