# Generated by Django 2.0.2 on 2018-03-31 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0004_auto_20180331_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='idRecruteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrumboard.Recruteur', verbose_name='recruteur'),
        ),
    ]
