# Generated by Django 2.0.2 on 2018-04-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0003_auto_20180405_0225'),
        ('scrumboard', '0004_auto_20180406_2050'),
    ]

    operations = [
    ]
