# Generated by Django 2.0.2 on 2018-03-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0005_auto_20180322_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruteur',
            name='logo',
            field=models.CharField(max_length=50),
        ),
    ]
