# Generated by Django 2.0.2 on 2018-04-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0005_auto_20180331_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='idRecruteur',
            new_name='idRecruteurs',
        ),
    ]
