# Generated by Django 2.0.2 on 2018-04-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0006_auto_20180402_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='idRecruteurs',
            new_name='idRecruteur',
        ),
    ]
