# Generated by Django 2.0.2 on 2018-03-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0006_auto_20180323_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruteur',
            name='logo',
            field=models.CharField(max_length=100),
        ),
    ]
