# Generated by Django 2.0.2 on 2018-04-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0007_offre_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruteur',
            name='nbOffres',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
