# Generated by Django 2.0.2 on 2018-04-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0007_auto_20180402_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='idRecruteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrumboard.Recruteur', verbose_name='idRecruteur_id'),
        ),
        migrations.AlterField(
            model_name='recruteur',
            name='recruteur_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Recruteur'),
        ),
    ]
