# Generated by Django 2.0.2 on 2018-04-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0008_recruteur_nboffres'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('tel', models.CharField(default=0, max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('civility', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('gouvernorate', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Candidat',
        ),
        migrations.AlterField(
            model_name='offre',
            name='dateAjout',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='offre',
            name='duree',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='offre',
            name='nature',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='offre',
            name='niveau',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
