# Generated by Django 2.0.2 on 2018-04-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0008_auto_20180402_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='idRecruteur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scrumboard.Recruteur', verbose_name='idRecruteur'),
        ),
    ]
