# Generated by Django 2.0.2 on 2018-04-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0011_candidat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='user',
        ),
        migrations.AlterField(
            model_name='recruteur',
            name='description',
            field=models.CharField(max_length=50000),
        ),
    ]
