# Generated by Django 2.0.2 on 2018-04-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0013_auto_20180430_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAjout', models.DateField(blank=True)),
                ('idCandidat', models.ManyToManyField(to='scrumboard.Candidat', verbose_name='idCandidat')),
                ('idOffre', models.ManyToManyField(to='scrumboard.Offre', verbose_name='idOffre')),
            ],
        ),
    ]
