# Generated by Django 2.0.2 on 2018-05-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0014_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
