# Generated by Django 2.0.2 on 2018-05-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0015_candidature_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='cv',
            field=models.FileField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
