# Generated by Django 2.0.2 on 2018-05-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0019_auto_20180501_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='cv',
        ),
    ]
