# Generated by Django 2.0.2 on 2018-05-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0020_remove_candidat_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
