# Generated by Django 2.0.2 on 2018-05-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0023_auto_20180501_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='cv',
            field=models.CharField(default=None, max_length=5000),
            preserve_default=False,
        ),
    ]
