# Generated by Django 2.0.2 on 2018-05-01 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0024_auto_20180501_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='idCandidat',
        ),
        migrations.AddField(
            model_name='candidature',
            name='idCandidat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scrumboard.Candidat', verbose_name='idCandidat'),
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='idOffre',
        ),
        migrations.AddField(
            model_name='candidature',
            name='idOffre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scrumboard.Offre', verbose_name='idOffre'),
        ),
    ]
