# Generated by Django 2.0.2 on 2018-05-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0025_auto_20180502_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='cvTxt',
            field=models.CharField(default=None, max_length=50000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidat',
            name='cv',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
