# Generated by Django 2.0.2 on 2018-05-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0027_auto_20180503_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='cvTxt',
            field=models.TextField(max_length=50000),
        ),
    ]
