# Generated by Django 2.0.2 on 2018-05-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0028_auto_20180503_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='idRecruteur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scrumboard.Recruteur', verbose_name='idRecruteur'),
        ),
    ]
