# Generated by Django 2.0.2 on 2018-05-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0030_remove_candidat_cvtxt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='owner',
        ),
    ]
